# Generated by Django 3.1 on 2020-08-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200822_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_size',
            new_name='size',
        ),
    ]
