# Generated by Django 3.1 on 2020-08-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
