# Generated by Django 3.1 on 2020-08-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200822_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='slug',
            new_name='sizeSlug',
        ),
    ]
