# Generated by Django 3.1 on 2020-08-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200822_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='sizeSlug',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='nfc_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
