# Generated by Django 3.1 on 2020-08-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200818_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='stock',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
