# Generated by Django 3.1 on 2020-08-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200822_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
