# Generated by Django 3.1 on 2020-08-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20200822_1214'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='timestamp',
            new_name='ordered_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='cart_items',
            field=models.ManyToManyField(to='carts.CartItem'),
        ),
    ]
