# Generated by Django 3.1 on 2020-08-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200822_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cart_items',
        ),
    ]
