# Generated by Django 3.1 on 2020-08-19 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_productvariation_stock'),
        ('orders', '0002_auto_20200819_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='CartItem',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(to='orders.CartItem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('I', 'In Cart'), ('O', 'Ordered'), ('F', 'Fulfilled'), ('C', 'Completed')], default=1, max_length=2),
        ),
    ]
