# Generated by Django 3.1 on 2020-08-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200822_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_charge_id',
        ),
    ]
